### ISSUE TITLE
Przycisk "Submit" w zakładce "Moje konto" powinien być zastąpiony polskim odpowiednikiem

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/volontulo#1072]
__Description:__

Przycisk "Submit" w zakładce "Moje konto" powinien być zastąpiony polskim odpowiednikiem.
![image](https://user-images.githubusercontent.com/22411234/46260658-30cd8700-c4e9-11e8-9c43-d348ff35682b.png)

__Current behaviour:__

Obecnie "Submit".

__Expected behaviour:__

Zmienić na "Zapisz".

**Comment by dagaaaaa** [comment]
#1076
