### ISSUE TITLE
Dodanie "Powtórz hasło" przy zakładaniu konta

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/volontulo#1074]
__Description:__

Jako niezalogowany użytkownik, który chce założyć konto, chciałabym aby oprócz pola "Hasło", pojawiało się pole "Powtórz hasło", abym mogła zweryfikować czy na pewno wprowadziłam takie hasło, jakie zamierzałam.

__Current behaviour:__

Obecnie mamy tylko jedno pole  - "Password".

__Expected behaviour:__

Pole "Password" powinno nazywać się "Hasło", a drugie pole do weryfikacji podanego ciągu znaków -  "Powtórz hasło".
Działanie na takiej samej zasadzie jak przy zmianie hasła.

![image](https://user-images.githubusercontent.com/22411234/46260855-e26db780-c4eb-11e8-9d0a-c2fe2b9c4a48.png)

**Comment by stanislawK** [comment]
biorę
