### ISSUE TITLE
Investigate code quality

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/volontulo#4]
As a new member on board, @riv2q requested an issue to get to know each other with the application investigate possibilities of code improvement. 

Outcome of the investigation will be posted in comments. Further issues will be raised separately.

**Comment by magul** [comment]
@riv2q do we need this issue, or have You done it already?

**Comment by magul** [comment]
Ok, I'm going to close it, as it doesn't make sense to have issue with no deliverable at all.
