### ISSUE TITLE
Fabric file need to be updated

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#417]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [magul](https://github.com/magul)**
_Monday Nov 09, 2015 at 11:45 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/373_

----

fabfile.py right now doesn't support new shape for project. For simplification of deployment it should be updated.

**Comment by magul** [comment]
Done. With every changeset that lands in master branch our fabfile update staging environment.
