### ISSUE TITLE
Datepicker for date/time fields

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#423]
<a href="https://github.com/Yog"><img src="https://avatars.githubusercontent.com/u/432220?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Yog](https://github.com/Yog)**
_Wednesday Jan 27, 2016 at 16:47 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/417_

----

on offer creation there are fields: 
![image](https://cloud.githubusercontent.com/assets/432220/12620747/c99cb894-c51d-11e5-95f6-4bdc23857441.png)
Add datepicker which will support year/month/day and hour 
and minutes possibly with 4 choices every 15 minutes 
and seconds dont matter, so hide them this or otehr way

**Comment by riv2q** [comment]
<a href="https://github.com/nbbn"><img src="https://avatars.githubusercontent.com/u/7264317?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nbbn](https://github.com/nbbn)**
_Friday Feb 26, 2016 at 21:33 GMT_

----

I'm doing it!

**Comment by magul** [comment]
Datepickers will be done in Angular, so if not, there will be a separate issue for that.
