### ISSUE TITLE
Images that are missing should not give 404

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#426]
<a href="https://github.com/Yog"><img src="https://avatars.githubusercontent.com/u/432220?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Yog](https://github.com/Yog)**
_Friday Jan 29, 2016 at 14:13 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/424_

----

If an offer, user and in future organization did not upload any image, the system doesn't check that and generates html that links to resource that isn't there, thus 404. 
Make sure that a placeholder image is linked when there is no image to display. 
This resource should likely not be in `/media/` but inside `/static/` instead. 
Alternatively a css class can be added, so we display background-color or background-image. 

Note that currently images are displayed eighter as `<img>` tags or as background images via css.

**Comment by riv2q** [comment]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magul](https://github.com/magul)**
_Friday Feb 26, 2016 at 23:26 GMT_

----

@KrzysztofMadejski

**Comment by w1stler** [comment]
Work as expected. Sign-off.
