### ISSUE TITLE
Error when create offer with no start date

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#427]
<a href="https://github.com/Yog"><img src="https://avatars.githubusercontent.com/u/432220?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Yog](https://github.com/Yog)**
_Wednesday Feb 03, 2016 at 16:01 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/426_

----

When you try to create offer with unspecified date, then you get error:
`Exception Value:   unorderable types: NoneType() < datetime.datetime()`

Offer is created however and awaits confirmation by admin

**Comment by w1stler** [comment]
Duplicate of #443
