### ISSUE TITLE
Admin user creation

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#428]
<a href="https://github.com/Yog"><img src="https://avatars.githubusercontent.com/u/432220?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Yog](https://github.com/Yog)**
_Wednesday Feb 03, 2016 at 16:51 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/428_

----

This account is crucial for complete offer flow. 
Admin user is owned by those who validate organization offers for public view. 
Currently it can only be created by changing flags directly in database. This can change by eighter:
1. first registered user will be an admin
2. if there is no admin, there is an additional checkbox on register form. If it is checked, then that account will be an admin
3. there is special url for `admin-reqistration` Where a reguistration form described in 2. is present
4. Admins could have ability to visit user profiles of others and select them as admins with a checkbox visible only to admins. An admin could possibly resign from being an admin this way
5. _Make it your own way._

**Comment by riv2q** [comment]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magul](https://github.com/magul)**
_Friday Feb 05, 2016 at 09:32 GMT_

----

Another (and prefered) way of creating admin user is making it possible using django script (like we are already initializing DB with badges).

**Comment by magul** [comment]
Closing it.
