### ISSUE TITLE
Introduce unicode_literals

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#432]
<a href="https://github.com/tomaszwozniak"><img src="https://avatars.githubusercontent.com/u/6023099?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomaszwozniak](https://github.com/tomaszwozniak)**
_Sunday Feb 21, 2016 at 17:45 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/437_

----

http://python-future.org/unicode_literals.html

**Comment by riv2q** [comment]
<a href="https://github.com/tomaszwozniak"><img src="https://avatars.githubusercontent.com/u/6023099?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomaszwozniak](https://github.com/tomaszwozniak)**
_Sunday Feb 21, 2016 at 17:46 GMT_

----

Can't add tags, but probably should be #tech and #enhancement

**Comment by riv2q** [comment]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magul](https://github.com/magul)**
_Sunday Feb 21, 2016 at 17:54 GMT_

----

@tomaszwozniak I've added tags - the reason You were not able to add labels is that You were not a member of @stxnext-csr/volontulodevs. But You're already, because I've added You. :)

**Comment by riv2q** [comment]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magul](https://github.com/magul)**
_Sunday Feb 21, 2016 at 17:58 GMT_

----

BTW I'm not certain, if we will fix this issue on hackathon (we will be focusing on MVP) and we have been focused on running it on Python 3 only, but we can introduce support for Python 2 if it's not difficult to be done.

**Comment by riv2q** [comment]
<a href="https://github.com/tomaszwozniak"><img src="https://avatars.githubusercontent.com/u/6023099?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomaszwozniak](https://github.com/tomaszwozniak)**
_Sunday Feb 21, 2016 at 18:03 GMT_

----

Ok I was confused because I've found lots of u" in the code :)

**Comment by magul** [comment]
I'm closing this one, as we decided only to support Python3 and we will remove `u` prefixes during other stories.
