### ISSUE TITLE
Mark all the required fields

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#435]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Tuesday Feb 23, 2016 at 22:11 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/442_

----

In order to fill in all the required fields
As a user
I want to see clearly which fields are required

The required fields are already marked as such in models and forms in application.

**Acceptance criteria**

1. Required fields are marked with red asterisk (see the mockups for a general idea how it's supposed to look like)
2. Required fields which were not filled should have validation as below:

![image](https://cloud.githubusercontent.com/assets/17498341/24714694/866ac130-1a29-11e7-8c6d-3374674dcf6b.png)

3. Defualt growl notification with text: "Formularz zawiera błędy."
4. Remove unnecessary information from growl notification (field names from django tepmlates, eg. phone_no)

![image](https://cloud.githubusercontent.com/assets/17498341/24714768/bac504b8-1a29-11e7-89b1-af2f6bd88edb.png)

![image](https://cloud.githubusercontent.com/assets/17498341/24714884/132cf368-1a2a-11e7-9071-eea78d73b2ac.png)

5. Keep consistent validation (see below picture for reference)

![image](https://cloud.githubusercontent.com/assets/17498341/24714959/4b79f91e-1a2a-11e7-9df9-165e13bbc1a1.png)

6. Please beware that there are also edit layouts. 

**Placement**

1. /login
2. /contact
3. /organizations/xxx/id
4. /offers/xxx/id/join
5. /organization/create

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Wednesday Feb 24, 2016 at 09:39 GMT_

----

![screenshot-at-09-15-13](https://cloud.githubusercontent.com/assets/15927677/13281224/cf75f232-dae2-11e5-9117-67ef94580d0d.png)

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Wednesday Feb 24, 2016 at 09:57 GMT_

----

![screenshot-at-09-34-43](https://cloud.githubusercontent.com/assets/15927677/13281672/7119648c-dae5-11e5-8faf-14e645a41226.png)

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 16:42 GMT_

----

Needs to be investigated if it is clearly marked in the database.

**Comment by w1stler** [comment]
Split story for every form.

**Comment by w1stler** [comment]
Splitting the story depends on amount of work (to be discussed).

**Comment by magul** [comment]
There is a lot to do here and we will try to resolve it during migration to Angular.
