### ISSUE TITLE
Change archived offers button and header

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#439]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Tuesday Feb 23, 2016 at 22:27 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/449_

----

http://volontuloapp.org/offers/archived

On admin panel there is an option to choose "Oferty archiwizowane". It should be renamed to "Archiwum ofert" to be consistent with the rest of the page.
This button is visible once you log in as an admin.

The header of http://volontuloapp.org/offers/archived should be renamed to "Archiwum ofert" as well.

**Comment by riv2q** [comment]
<a href="https://github.com/mdziergwa"><img src="https://avatars.githubusercontent.com/u/633953?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdziergwa](https://github.com/mdziergwa)**
_Friday Feb 26, 2016 at 20:26 GMT_

----

biorę

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 21:32 GMT_

----

up for grabs since @mdziergwa left already

**Comment by riv2q** [comment]
<a href="https://github.com/Ziachu"><img src="https://avatars.githubusercontent.com/u/9215324?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Ziachu](https://github.com/Ziachu)**
_Friday Feb 26, 2016 at 23:09 GMT_

----

in progress...

**Comment by w1stler** [comment]
Work as expected. Sign-off.
