### ISSUE TITLE
I want to delete the pictures in my offer

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#441]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Tuesday Feb 23, 2016 at 22:43 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/455_

----

In order to have the pictures displayed with my offer
As an organization
I want to delete the pictures in my offer

AC
1. A small X is displayed in the top right corner on every picture
2. A click on the X deletes the picture from the offer

![screenshot-at-13-37-51](https://cloud.githubusercontent.com/assets/15927677/13319953/9f3a4dc8-dbc5-11e5-8f05-dc083a809b43.png)

**Comment by w1stler** [comment]
Duplicate #479
