### ISSUE TITLE
Contact the organization - the email is sent to the user

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#442]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Wednesday Feb 24, 2016 at 08:01 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/457_

----

When  a user goes into organization info under e.g. http://volontuloapp.org/organizations/fundacja-taka-sytuacja/9 and contacts the organization, the email is not sent to the organization, but to the user.

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Thursday Feb 25, 2016 at 10:52 GMT_

----

Needs to be done after #444 is completed

**Comment by w1stler** [comment]
Remove user that fills contact form from email recevers list

**Comment by w1stler** [comment]
End user is not receiving email, but mail is also sent to address: ddd.

![image](https://cloud.githubusercontent.com/assets/17498341/24214109/dc052f90-0f34-11e7-9e9d-35abde40c1e0.png)

**Comment by w1stler** [comment]
Randomly created user (ddd@ddd.pl) was assigned to this Organization as well. Work as expected. SIgn-off.
