### ISSUE TITLE
As an admin I can verify ogranisations' offers

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#444]
<a href="https://github.com/bakalaw"><img src="https://avatars.githubusercontent.com/u/17060713?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bakalaw](https://github.com/bakalaw)**
_Wednesday Feb 24, 2016 at 10:03 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/462_

----

In order to verify unpublished offers (pending admin's approval)
As an admin
I want to see unverified offers on http://volontuloapp.org/panel

AC: 
- Entering the admin panel from the dropdown an admin gets to the http://volontuloapp.org/panel
- List of unpublished offers for verification is displayed
- "Edytuj" and "Podgląd" buttons are hidden (both actions can be easily done without these particular buttons)
- Buttons with actions to Accept or Delete an offer next to each one
- Admin can publish or reject an offer 
- After chosing delete as an action, the pop-up appears to ensure the admin really wants an offer to be deleted
- Deleted (rejected) offers get status is_deleted and are not deleted permanently, only hidden for users, but visible for the admin in the archived section

See the attached picture for an overview how it should look like. Of course, the styling is rough and a neat solution needs to be applied.

![screenshot-at-09-11-23](https://cloud.githubusercontent.com/assets/15927677/13358222/797164ac-dcae-11e5-9616-33d050435ba0.png)

**Comment by riv2q** [comment]
<a href="https://github.com/mpuhacz"><img src="https://avatars.githubusercontent.com/u/2760666?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpuhacz](https://github.com/mpuhacz)**
_Friday Feb 26, 2016 at 17:48 GMT_

----

biorę

**Comment by riv2q** [comment]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [w1stler](https://github.com/w1stler)**
_Thursday Sep 15, 2016 at 17:12 GMT_

----

Moving to merged column: https://travis-ci.org/stxnext-csr/volontulo/builds/112153078

**Comment by magul** [comment]
There is an option to activate offer on simple offers list (if You're logged in as an admin). I would suggest not to waste our time on this story as it doesn't looks refined properly and it doesn't look like critical bug/enhancement.
