### ISSUE TITLE
As an organisation I can edit my offer

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#446]
<a href="https://github.com/bakalaw"><img src="https://avatars.githubusercontent.com/u/17060713?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bakalaw](https://github.com/bakalaw)**
_Wednesday Feb 24, 2016 at 10:07 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/464_

----

AC:
- Organisation can edit only unpublished offers (pending approval by the admin)
- The Edit button is displayed only next to unpublished offers

**Comment by w1stler** [comment]
Duplicate #449
