### ISSUE TITLE
Admin can easily navigate to admin panel

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#447]
<a href="https://github.com/bakalaw"><img src="https://avatars.githubusercontent.com/u/17060713?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bakalaw](https://github.com/bakalaw)**
_Wednesday Feb 24, 2016 at 10:13 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/466_

----

In order to see the homepage and easily get to the admin panel
As an admin
I want to have admin panel as a selection in the dropdown that appears when I click on the email address.

AC:
1. main page with a drop down which navigates to an admin panel
2. the field should be named "Panel administracyjny" 
3. This dropdown field is linked to the sub-page http://volontuloapp.org/panel that needs to be created

![](https://cloud.githubusercontent.com/assets/17060713/13295932/6e69abf2-db2b-11e5-8a38-db68291d754f.png)

**Comment by riv2q** [comment]
<a href="https://github.com/Ziachu"><img src="https://avatars.githubusercontent.com/u/9215324?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Ziachu](https://github.com/Ziachu)**
_Friday Feb 26, 2016 at 18:25 GMT_

----

in progress...

**Comment by riv2q** [comment]
<a href="https://github.com/bakalaw"><img src="https://avatars.githubusercontent.com/u/17060713?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bakalaw](https://github.com/bakalaw)**
_Friday Feb 26, 2016 at 23:22 GMT_

----

Actually I can't see a drop down with "Panel admiński"

**Comment by riv2q** [comment]
<a href="https://github.com/Ziachu"><img src="https://avatars.githubusercontent.com/u/9215324?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Ziachu](https://github.com/Ziachu)**
_Friday Feb 26, 2016 at 23:30 GMT_

----

> 2. the field should be named "Panel administracyjny" 

Which is more important, picture or text?

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 23:31 GMT_

----

Let's go with Panel administracyjny here. Still, the dropdown field is not there.

**Comment by w1stler** [comment]
@magul, can you verify if this feature was deployed?

![image](https://cloud.githubusercontent.com/assets/17498341/22079971/0ce20de8-ddbe-11e6-8861-2f79ff11bc42.png)

**Comment by w1stler** [comment]
Feature should be deployed to live env.

**Comment by w1stler** [comment]
Work as expected on docker env. Sign-off.
