### ISSUE TITLE
As an admin I can edit content 

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#448]
<a href="https://github.com/bakalaw"><img src="https://avatars.githubusercontent.com/u/17060713?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bakalaw](https://github.com/bakalaw)**
_Wednesday Feb 24, 2016 at 10:15 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/467_

----

AC
There is a CMS tool for rendering the content onto the website (raw HTML)

**Comment by riv2q** [comment]
<a href="https://github.com/Yog"><img src="https://avatars.githubusercontent.com/u/432220?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Yog](https://github.com/Yog)**
_Friday Feb 26, 2016 at 11:13 GMT_

----

duplicate of https://github.com/stxnext-csr/volontulo/issues/397 and https://github.com/stxnext-csr/volontulo/issues/396

**Comment by riv2q** [comment]
<a href="https://github.com/tomaszwozniak"><img src="https://avatars.githubusercontent.com/u/6023099?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomaszwozniak](https://github.com/tomaszwozniak)**
_Friday Feb 26, 2016 at 17:59 GMT_

----

Missing list of pages.

**Comment by riv2q** [comment]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magul](https://github.com/magul)**
_Friday Feb 26, 2016 at 18:32 GMT_

----

@tomaszwozniak list of pages is in #477

**Comment by riv2q** [comment]
<a href="https://github.com/mpuhacz"><img src="https://avatars.githubusercontent.com/u/2760666?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpuhacz](https://github.com/mpuhacz)**
_Friday Feb 26, 2016 at 21:04 GMT_

----

I take it with #477

**Comment by riv2q** [comment]
<a href="https://github.com/KrzysztofMadejski"><img src="https://avatars.githubusercontent.com/u/849975?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KrzysztofMadejski](https://github.com/KrzysztofMadejski)**
_Friday Feb 26, 2016 at 21:14 GMT_

----

@mpuhacz will you use https://docs.djangoproject.com/en/1.9/ref/contrib/flatpages/ ?

**Comment by riv2q** [comment]
<a href="https://github.com/mpuhacz"><img src="https://avatars.githubusercontent.com/u/2760666?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpuhacz](https://github.com/mpuhacz)**
_Friday Feb 26, 2016 at 21:17 GMT_

----

@KrzysztofMadejski At first I wanted to use it, but it is dependent on django.contrib.sites, so after all I'm going to create new model with fields:
title, html, userprofile, modified_at and created_at. What do you think?

**Comment by riv2q** [comment]
<a href="https://github.com/KrzysztofMadejski"><img src="https://avatars.githubusercontent.com/u/849975?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KrzysztofMadejski](https://github.com/KrzysztofMadejski)**
_Friday Feb 26, 2016 at 21:21 GMT_

----

I haven't used it, but from what I've read I understand it has wysiwyg editor and the whole admin. Seems like the easiest option.

**Comment by riv2q** [comment]
<a href="https://github.com/mpuhacz"><img src="https://avatars.githubusercontent.com/u/2760666?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpuhacz](https://github.com/mpuhacz)**
_Friday Feb 26, 2016 at 21:34 GMT_

----

@KrzysztofMadejski, true - it has **django** admin, but we want to display edit form inside "bussines-admin"(dunno how to call it), so anyway I'll have to write new views.

**Comment by w1stler** [comment]
@magul, can you verify if this feature was deployed?

**Comment by w1stler** [comment]
Feature should be deployed to live env.
