### ISSUE TITLE
As an organisation I can edit only my offer

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#449]
<a href="https://github.com/bakalaw"><img src="https://avatars.githubusercontent.com/u/17060713?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bakalaw](https://github.com/bakalaw)**
_Wednesday Feb 24, 2016 at 12:40 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/470_

----

AC - 
Organisation has a list of its offers.
Organisation can edit only its offers.
The button "Edit" next to another organization's offers should be hidden

Currently editing other organization's is not possible even though the edit button is displayed. After clicking on it following error is displayed
![screenshot-at-09-02-47](https://cloud.githubusercontent.com/assets/15927677/13346604/b67db75c-dc67-11e5-8dcb-ef9260fd6ab2.png)

**Comment by riv2q** [comment]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [w1stler](https://github.com/w1stler)**
_Thursday Sep 15, 2016 at 18:25 GMT_

----

Moving to Merged column: https://travis-ci.org/stxnext-csr/volontulo/builds/112117373

**Comment by magul** [comment]
Done
