### ISSUE TITLE
Hide "Edit" button for a volunteer/user 

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#451]
<a href="https://github.com/bakalaw"><img src="https://avatars.githubusercontent.com/u/17060713?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bakalaw](https://github.com/bakalaw)**
_Wednesday Feb 24, 2016 at 18:48 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/473_

----

logged in user/volunteer shouldn't see "Edytuj" button
unregistered user shuldn't see "Edytuj" button
"Edytuj" button should be visible only for organization that created that particular offer and admin users
![ukryc edytuj](https://cloud.githubusercontent.com/assets/17060713/13296766/74df915a-db2f-11e5-8816-2008d74917c2.png)

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 08:13 GMT_

----

A similar issue, but described from the organization's POV is described in #470

**Comment by w1stler** [comment]
Already fixed.
