### ISSUE TITLE
User account view needs to be reorganized

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#452]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Thursday Feb 25, 2016 at 10:08 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/475_

----

http://volontuloapp.org/me

AC
1. The whole field with "Użytkownik: <mail>" (with both user IDs) and "Odznaki" needs to be hidden.
2. The profile picture needs to be moved to the "Zdjęcie profilowe" section.
3. There should be an option to delete the avatar, not only to replace it.
4. Before deleting the picture a pop-up should appear to confirm the decision.
5. "Użyć jako avatar?" checkbox should be hidden (described in #474)

Please, find a "mock-up" attached to see how the new layout should look.
![screenshot-at-10-59-11](https://cloud.githubusercontent.com/assets/15927677/13316374/12b27a20-dbb0-11e5-9e1e-27aa43442a1f.png)

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 22:15 GMT_

----

Who is doing that? apart from @radoslawroszkowiak

**Comment by magul** [comment]
closing this one.
