### ISSUE TITLE
A vertically-oriented offer picture is displayed horizontally

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#453]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Thursday Feb 25, 2016 at 12:49 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/476_

----

The bug occurs in both places that allow a user to upload a picture: as an avatar on the account page and as an offer picture in the offer creation/editing.
When a vertically-oriented picture is uploaded it is displayed as a horizontally-oriented one turner 90 degrees to the left.
![screenshot-at-13-49-17](https://cloud.githubusercontent.com/assets/15927677/13320082/8f4f9ade-dbc6-11e5-89c8-ed47b2a828f3.png)

**Comment by riv2q** [comment]
<a href="https://github.com/rooterkyberian"><img src="https://avatars.githubusercontent.com/u/637466?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rooterkyberian](https://github.com/rooterkyberian)**
_Thursday Feb 25, 2016 at 17:43 GMT_

----

Fragment of exif of picture in question:
> Orientation                     : Rotate 90 CW
> Camera Orientation              : Rotate 90 CW

**Comment by w1stler** [comment]
Probably invalid.

**Comment by w1stler** [comment]
Issue still occurs. Using ibimage-exiftool-perl I have verified the Rotation of attached file and it states 90 CW Rotation. Image is properly displayed in Firefox. We should consider adding exif tools to automatically verify the rotation and adjusting it accordingly. 
![p1020148-magicked](https://cloud.githubusercontent.com/assets/17498341/23963995/4b70c3b2-09b3-11e7-845a-47ba2a1c0af4.jpg)

**Comment by magul** [comment]
Closing this one as really wired situation.
