### ISSUE TITLE
Add page content - HTML static

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#454]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Thursday Feb 25, 2016 at 13:01 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/477_

----

In order to have some more information about volontulo
As a user
I want to see "Regulamin", "FAQ dla organizacji" and "FAQ dla wolontariuszy".

AC
There is a static HTML in the sections "Regulamin", "FAQ dla organizacji" and "FAQ dla wolontariuszy".
FAQs should be formatted with the existing question-answer rules.

The content should be taken from here: 
Regulamin: #286 
FAQ dla organizacji: #285 
FAQ dla wolontariuszy: #284

**Comment by riv2q** [comment]
<a href="https://github.com/mpuhacz"><img src="https://avatars.githubusercontent.com/u/2760666?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpuhacz](https://github.com/mpuhacz)**
_Friday Feb 26, 2016 at 21:04 GMT_

----

I take it with #467

**Comment by w1stler** [comment]
Will be done in #409, #410 and #408
