### ISSUE TITLE
Add WYSIWYG

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#455]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Thursday Feb 25, 2016 at 13:29 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/478_

----

WYSIWYG methods are used so the content added in CMS can be displayed in the same form on the website.

**Comment by magul** [comment]
There's no CMS
