### ISSUE TITLE
Add a big baner on the homepage

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#456]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Thursday Feb 25, 2016 at 21:55 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/482_

----

In order to get a user familiar with the system
As an admin
I want to have a graphic representation of the website's purpose

AC
The banner should be place in the placeholder on the homepage

![98aab242-dcc2-11e5-8836-25676c6d04ab](https://cloud.githubusercontent.com/assets/15927677/13362164/07056ef8-dcc3-11e5-9b99-1f0d3e618f35.png)

**Comment by riv2q** [comment]
<a href="https://github.com/doslizlo"><img src="https://avatars.githubusercontent.com/u/556392?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [doslizlo](https://github.com/doslizlo)**
_Friday Feb 26, 2016 at 18:50 GMT_

----

New version of the banner.
![hero_bg_new](https://cloud.githubusercontent.com/assets/556392/13361998/3e675790-dcc2-11e5-92fe-5bfede17ada6.png)

**Comment by riv2q** [comment]
<a href="https://github.com/doslizlo"><img src="https://avatars.githubusercontent.com/u/556392?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [doslizlo](https://github.com/doslizlo)**
_Friday Feb 26, 2016 at 18:55 GMT_

----

And even the newer one. This one's accepted.

![hero_bg_new2](https://cloud.githubusercontent.com/assets/556392/13362066/98aab242-dcc2-11e5-8836-25676c6d04ab.png)

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 18:56 GMT_

----

ticket updated

**Comment by w1stler** [comment]
Already on prod.
