### ISSUE TITLE
Special information displayed when a user without an organization wants to create an offer

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#457]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 09:28 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/485_

----

When a user that does not have an organization enters the http://volontuloapp.org/offers/create subsite, the information "Nie masz jeszcze żadnej założonej organizacji na volontuloapp.org. Aby założyć organizację, kliknij tu." is displayed.

Under "tu" there is a link to http://volontuloapp.org/organizations/create

**Comment by riv2q** [comment]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [w1stler](https://github.com/w1stler)**
_Friday Feb 26, 2016 at 19:07 GMT_

----

Suggestion: "Aby założyć organizację kliknij tu." -> adding comma between two verbs within the sentence: "Aby założyć organizację, kliknij tu."

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 19:10 GMT_

----

updated

**Comment by riv2q** [comment]
<a href="https://github.com/mkwiat79"><img src="https://avatars.githubusercontent.com/u/3657635?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mkwiat79](https://github.com/mkwiat79)**
_Friday Feb 26, 2016 at 23:04 GMT_

----

MOJE

**Comment by riv2q** [comment]
<a href="https://github.com/mkwiat79"><img src="https://avatars.githubusercontent.com/u/3657635?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mkwiat79](https://github.com/mkwiat79)**
_Saturday Feb 27, 2016 at 00:05 GMT_

----

PR raised

**Comment by riv2q** [comment]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [w1stler](https://github.com/w1stler)**
_Thursday Sep 01, 2016 at 17:25 GMT_

----

I have created Merged pipeline. PR was already merged, moving forward.

**Comment by riv2q** [comment]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [w1stler](https://github.com/w1stler)**
_Thursday Sep 01, 2016 at 17:27 GMT_

----

Feautre's already on production.

**Comment by riv2q** [comment]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magul](https://github.com/magul)**
_Friday Sep 02, 2016 at 09:22 GMT_

----

Shouldn't we close it? @w1stler

**Comment by riv2q** [comment]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [w1stler](https://github.com/w1stler)**
_Friday Sep 02, 2016 at 09:23 GMT_

----

I'd prefer this to be tested first.

**Comment by riv2q** [comment]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magul](https://github.com/magul)**
_Friday Sep 02, 2016 at 09:25 GMT_

----

Ach, ok, I haven't seen pipiline :)

**Comment by w1stler** [comment]
Moving to sign-off, user without organization is moved to /offers and proper message is displayed. 

![image](https://cloud.githubusercontent.com/assets/17498341/22078349/fe0554f2-ddb7-11e6-92f1-684fb0c638d8.png)
