### ISSUE TITLE
Refactor of organization's section in the footer

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#459]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 11:14 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/488_

----

The middle section in the footer should be renamed to STREFA ORGANIZACJI I INSTYTUCJI with sub-sites for organizations.
The section should contain:
Załóż konto (http://volontuloapp.org/register)
Dodaj nową ofertę (http://volontuloapp.org/offers/create)
Lista organizacji i instytucji (http://volontuloapp.org/organizations)
FAQ dla organizacji i instytucji (http://volontuloapp.org/pages/faq-organizations)
Przyjdź na dyżur (http://volontuloapp.org/office)

![screenshot-at-11-00-50](https://cloud.githubusercontent.com/assets/15927677/13350777/87bec710-dc82-11e5-8b5c-543cfce14a53.png)

**Comment by riv2q** [comment]
<a href="https://github.com/tiriana"><img src="https://avatars.githubusercontent.com/u/5216143?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tiriana](https://github.com/tiriana)**
_Friday Feb 26, 2016 at 19:25 GMT_

----

@zuzannawiler 
"
The **middle** section in the footer 
"

What is right - the image or the description ? :) Should "strefa wolontariusza" be in th middle or on the right?

**Comment by riv2q** [comment]
<a href="https://github.com/KrzysztofMadejski"><img src="https://avatars.githubusercontent.com/u/849975?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KrzysztofMadejski](https://github.com/KrzysztofMadejski)**
_Friday Feb 26, 2016 at 19:26 GMT_

----

`Przyjdź na dyżur` is doubled - it's also in the third section - is this planned?

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 19:27 GMT_

----

I got lost in copy-paste. this ticket is about organizations, so the middle section. the mockup is the right version.

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 19:27 GMT_

----

@KrzysztofMadejski yes. let's stay true to the mockup

**Comment by riv2q** [comment]
<a href="https://github.com/tiriana"><img src="https://avatars.githubusercontent.com/u/5216143?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tiriana](https://github.com/tiriana)**
_Friday Feb 26, 2016 at 19:28 GMT_

----

@KrzysztofMadejski Would you like to do this one?

**Comment by riv2q** [comment]
<a href="https://github.com/nbbn"><img src="https://avatars.githubusercontent.com/u/7264317?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nbbn](https://github.com/nbbn)**
_Friday Feb 26, 2016 at 19:42 GMT_

----

In progress by me!

**Comment by w1stler** [comment]
Done, tested on prod. Just one question - do we need to have three links to /register page? ;-)

**Comment by w1stler** [comment]
We should remove the Newsletter link from the footer (at least at the moment). Reference: #458

**Comment by w1stler** [comment]
Newsletter removed.
