### ISSUE TITLE
http://volontuloapp.org/offers/reorder/ Drag&Drop ordering needs to be applied

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#460]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 16:02 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/492_

----

In order to easily reorder the offers on the homepage
As an admin
I want to have a Drag&Drop applied to the ordering

AC
Offers are ordered by Drag&Drop
The save is done after dropping an element
The button "Zapisz" at the top of the list is hidden

**Comment by magul** [comment]
Closing this one.
