### ISSUE TITLE
Admin Panel layout

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#461]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 16:16 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/494_

----

Entering http://volontuloapp.org/panel the admin sees his admin panel. 4 buttons are visible at the top of the page.
Niezweryfikowane oferty - a list of unpublished offers pending admin verification (a default one, on http://volontuloapp.org/panel)
Kolejność ofert na stronie głównej - a place to reorder offers on the homepage (http://volontuloapp.org/offers/reorder/)
Lista ofert - a complete list of ongoing and future events (http://volontuloapp.org/offers)
Oferty archiwizowane - a complete list of finished or rejected offers (http://volontuloapp.org/offers/archived)

Going into any one of this sub-pages, an admin can still see this 4 buttons at the top of the page.
![screenshot-at-17-16-50](https://cloud.githubusercontent.com/assets/15927677/13357851/b5f1510a-dcac-11e5-9228-caa080b1c1be.png)

**Comment by riv2q** [comment]
<a href="https://github.com/Ziachu"><img src="https://avatars.githubusercontent.com/u/9215324?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Ziachu](https://github.com/Ziachu)**
_Friday Feb 26, 2016 at 19:14 GMT_

----

in progress

**Comment by w1stler** [comment]
Already done.
