### ISSUE TITLE
An inactive logged out user wants to sign up for an offer

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#462]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 16:56 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/496_

----

After filling in the form to sign up for an offer, the system recognizes a user as an inactive user and at the top of the page displayes the information "Konto jest nieaktywne. Aby w pełni korzystać ze swojego konta, aktywuj je poprzez link aktywacyjny wysłany na adres mailowy lub skontaktuj się z administratorem.".
After activating the account and logging in, the user gets a confirmation "Zgłoszenie chęci uczestnictwa zostało wysłane." and is already signed for the offer.

**Comment by riv2q** [comment]
<a href="https://github.com/Gruszks"><img src="https://avatars.githubusercontent.com/u/35410?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Gruszks](https://github.com/Gruszks)**
_Friday Feb 26, 2016 at 21:40 GMT_

----

User have to explicity sign up for an offer, this will be removed:
After activating the account and logging in, the user gets a confirmation "Zgłoszenie chęci uczestnictwa zostało wysłane." and is already signed for the offer.

**Comment by w1stler** [comment]
Duplicate #480
