### ISSUE TITLE
Fix issue with deploying application on staging environment

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#463]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [magul](https://github.com/magul)**
_Friday Feb 26, 2016 at 18:54 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/502_

----

**Comment by magul** [comment]
It's right now working properly. With every commit that lands in master branch Travis is updating staging environment.
