### ISSUE TITLE
contact form on offer of applied volunteers can't be opened

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#465]
<a href="https://github.com/Margaret2015"><img src="https://avatars.githubusercontent.com/u/14870366?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Margaret2015](https://github.com/Margaret2015)**
_Friday Feb 26, 2016 at 20:42 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/519_

----

**Comment by w1stler** [comment]
Invalid.
