### ISSUE TITLE
Dates of the offers

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#467]
<a href="https://github.com/Margaret2015"><img src="https://avatars.githubusercontent.com/u/14870366?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Margaret2015](https://github.com/Margaret2015)**
_Friday Feb 26, 2016 at 22:48 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/536_

----

If there is no date of the beginning of the action in offer and if there is no the end of the action should be the information "rekrutacja ciągła", not "od teraz do ustalenia". Also if there is the date of the beginning of the action in offer, but there is no the end of the action should be the information "rekrutacja ciągła" instead of "do ustalenia".

**Comment by w1stler** [comment]
Verify all of the scenarios.

**Comment by magul** [comment]
Closing this one. We have a lot to do, so we decided, that we will fix this one, when it will bother somebody.
