### ISSUE TITLE
CRITICAL BUG!!!! A regular user can access admin panel

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#470]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Friday Feb 26, 2016 at 23:28 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/543_

----

As a regular user I can access admin panel by clicking on http://volontuloapp.org/offers/archived or http://volontuloapp.org/offers in the footer.

It needs to be fixed!

TOP PRIORITY

**Comment by riv2q** [comment]
<a href="https://github.com/KrzysztofMadejski"><img src="https://avatars.githubusercontent.com/u/849975?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KrzysztofMadejski](https://github.com/KrzysztofMadejski)**
_Friday Feb 26, 2016 at 23:41 GMT_

----

Biorę to

**Comment by riv2q** [comment]
<a href="https://github.com/KrzysztofMadejski"><img src="https://avatars.githubusercontent.com/u/849975?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KrzysztofMadejski](https://github.com/KrzysztofMadejski)**
_Saturday Feb 27, 2016 at 00:11 GMT_

----

Zacząłem grzebać, ale jest niestandardowo zrealizowane logowanie. Nie działają helpery `{{user.is_staff}}`, dekoratory `@login_required` też nie (przekierowują na logowanie, po czym dostaje się komunikat "jesteś już zalogowany"). Trzeba by to od początku ogarnąć.

Rezygnuję z tego

**Comment by riv2q** [comment]
<a href="https://github.com/KrzysztofMadejski"><img src="https://avatars.githubusercontent.com/u/849975?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KrzysztofMadejski](https://github.com/KrzysztofMadejski)**
_Saturday Feb 27, 2016 at 00:12 GMT_

----

Jak będzie to robić to warto podbić Django do 1.9, żeby skorzystać z mixins do Class Views lub dołączyć projekt https://github.com/brack3t/django-braces

**Comment by riv2q** [comment]
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zuzannawiler](https://github.com/zuzannawiler)**
_Saturday Feb 27, 2016 at 00:13 GMT_

----

Przed hackatonem musiało to być jakoś rozwiązane i działało. Można jakoś zaczerpnąć rozwiązanie z poprzedniej wersji?

**Comment by magul** [comment]
I'm closing it as duplicate of #521
