### ISSUE TITLE
section: kontakt z administratorem

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#473]
<a href="https://github.com/Margaret2015"><img src="https://avatars.githubusercontent.com/u/14870366?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Margaret2015](https://github.com/Margaret2015)**
_Saturday Feb 27, 2016 at 00:16 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/549_

----

after when You click section: kontakt z administratorem, You will move to place for login/ To clarify, if the contact with the admin only by login or/also by form

**Comment by w1stler** [comment]
Duplicate #474
