### ISSUE TITLE
Section "Kontakt z administratorem" accessible without login

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#474]
<a href="https://github.com/Margaret2015"><img src="https://avatars.githubusercontent.com/u/14870366?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Margaret2015](https://github.com/Margaret2015)**
_Saturday Feb 27, 2016 at 00:17 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/551_

----

When we click on "Kontakt z administratorem" then appears "Logowanie".

Contact with admin should be enabled without logging in.

**Comment by w1stler** [comment]
There is an issue - in case using of using form as organization ("Kontaktuję się jako: organizacja"), user still gets email which states: "Kontakt wolontariusza z administratorem".

**Comment by w1stler** [comment]
Work as expected.
