### ISSUE TITLE
Create Docker File for new environment

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#481]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [w1stler](https://github.com/w1stler)**
_Thursday Aug 11, 2016 at 17:47 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/568_

----

As a new programmer,
I want to easily set-up new environment,
In order to start work on tickets

**Comment by riv2q** [comment]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [w1stler](https://github.com/w1stler)**
_Thursday Sep 01, 2016 at 16:48 GMT_

----

Moved to Pull Requests

**Comment by w1stler** [comment]
PR to be moved

**Comment by magul** [comment]
done
