### ISSUE TITLE
Create Vagrant File for new environment

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#482]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [w1stler](https://github.com/w1stler)**
_Thursday Aug 11, 2016 at 17:48 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/569_

----

As a new programmer,
I want to easily set-up new environment,
In order to start work on tickets

**Comment by riv2q** [comment]
<a href="https://github.com/krzysztofzuraw"><img src="https://avatars.githubusercontent.com/u/9116238?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [krzysztofzuraw](https://github.com/krzysztofzuraw)**
_Tuesday Aug 30, 2016 at 06:14 GMT_

----

@magul we want to go ansible or fabric? I'm more onto fabric because:
1. we already have fabfile
2. it is easier than ansible to setup

What do you think?

**Comment by riv2q** [comment]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magul](https://github.com/magul)**
_Tuesday Aug 30, 2016 at 08:07 GMT_

----

@krzysztofzuraw fabric it is!

**Comment by w1stler** [comment]
Duplicate, closing

#495
