### ISSUE TITLE
Update readme file (Docker + Vagrant)

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#483]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [w1stler](https://github.com/w1stler)**
_Thursday Aug 11, 2016 at 17:52 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/570_

----

As a new programmer,
I want to easily set-up new environment,
In order to start work on tickets

Update readme file with information related to Docker and Vagrant

**Comment by magul** [comment]
Proper description was created in wiki. We should point to it in `README.md`.

**Comment by magul** [comment]
That's already done.
