### ISSUE TITLE
Amend Volontulo description in readme

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#486]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [w1stler](https://github.com/w1stler)**
_Thursday Aug 11, 2016 at 18:09 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/573_

----

As a new participant,
I want to read project description,
In order to easily understand the purpose of application

**Comment by magul** [comment]
Closing
