### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#488]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [w1stler](https://github.com/w1stler)**
_Thursday Aug 11, 2016 at 18:30 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/575_

----

As a new participant,
I want to read project working agreement,
In order to easily understand the flow 

We have decided to update the workflow, so the new and current users will easily understand, how the working agreement looks like. 

The scheme would be as follows:

Refinement -> To do -> In progress -> Pull Request -> Merged -> Test -> Sign off

**Comment by riv2q** [comment]
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [w1stler](https://github.com/w1stler)**
_Thursday Sep 01, 2016 at 18:58 GMT_

----

I have created Merged pipeline. Stories in progress and PR should be reviewed.

**Comment by magul** [comment]
That should be described in wiki (there's already a manual for contributor made by @riv2q ).

**Comment by magul** [comment]
@OtisRed

**Comment by w1stler** [comment]
Update file with release cycles. 

https://github.com/CodeForPoznan/volontulo/issues/654#issuecomment-332563026

**Comment by w1stler** [comment]
Update with release cycles done (PR: https://github.com/CodeForPoznan/volontulo/pull/732), readme to be done within Community (how flow looks in gerenal).
