### ISSUE TITLE
docker and docker-compose configuration (fixes #568)

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#489]
<a href="https://github.com/magul"><img src="https://avatars.githubusercontent.com/u/1165138?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [magul](https://github.com/magul)**
_Wednesday Aug 24, 2016 at 22:14 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/pull/577_

----

**Story / Bug id:** https://github.com/stxnext-csr/volontulo/issues/568
**Reference person:** @magul
**Description:**

Providing docker and docker-compose configuration for development environment.

To setup it:
- install docker and docker-compose
- execute `docker-compose up`
- point your browser to `localhost:8000`

**New imports / dependencies:**
- N/A

**Unit Tests:**
- N/A

**What tests do I need to run to validate this change:**

Procedure described above.

----

_**[magul](https://github.com/magul)** included the following code: https://github.com/stxnext-csr/volontulo/pull/577/commits_

**Comment by riv2q** [comment]
<a href="https://github.com/codecov-io"><img src="https://avatars.githubusercontent.com/u/8655789?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [codecov-io](https://github.com/codecov-io)**
_Wednesday Aug 24, 2016 at 22:18 GMT_

----

## [Current coverage](https://codecov.io/gh/stxnext-csr/volontulo/pull/577?src=pr) is 91.26% (diff: 100%)
> Merging [#577](https://codecov.io/gh/stxnext-csr/volontulo/pull/577?src=pr) into [master](https://codecov.io/gh/stxnext-csr/volontulo/branch/master?src=pr) will not change coverage


```diff
@@             master       #577   diff @@
==========================================
  Files            53         53          
  Lines          2073       2073          
  Methods           0          0          
  Messages          0          0          
  Branches          0          0          
==========================================
  Hits           1892       1892          
  Misses          181        181          
  Partials          0          0          
```

> Powered by [Codecov](https://codecov.io?src=pr). Last update [5a7a192...1e04a0c](https://codecov.io/gh/stxnext-csr/volontulo/compare/5a7a1920c150dd5d19b95efc57c071279f307e44...1e04a0c2303ba807366672d38cadc67775482c82?src=pr)

**Comment by riv2q** [comment]
<a href="https://github.com/tomaszwozniak"><img src="https://avatars.githubusercontent.com/u/6023099?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomaszwozniak](https://github.com/tomaszwozniak)**
_Thursday Aug 25, 2016 at 16:01 GMT_

----

minor comments

**Comment by riv2q** [comment]
<a href="https://github.com/krzysztofzuraw"><img src="https://avatars.githubusercontent.com/u/9116238?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [krzysztofzuraw](https://github.com/krzysztofzuraw)**
_Friday Aug 26, 2016 at 11:23 GMT_

----

:+1: just one suggestion

**Comment by magul** [comment]
That was merged. Closing
