### ISSUE TITLE
Statics within Django admin panel

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/volontulo#508]
BUG: fix styles within Django admin panel. 

![image](https://cloud.githubusercontent.com/assets/17498341/22081172/ce38a4bc-ddc2-11e6-9d43-1e355d605630.png)

**Comment by magul** [comment]
There was a problem with `apache` configuration - it was pointing to `static` directory inside `volontulo` app instead to global, project `static`. It shoul server statics properly right now.
