### ISSUE TITLE
White marks on "Tworzenie organizacji" form

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/volontulo#514]
Steps to reproduce:

- Login as regular user
- Go to Organization creation page (http://volontuloapp.org/organizations/create)
- Fill the form with white marks
- Submit the form

Current behaviour:

- User is notified about Internal Server Error

Expected behaviour:

- Fields should be validated
- User should be prompted, that fields need to be filled

**Comment by juliaanholcer** [comment]
Solved with #892
