### ISSUE TITLE
Validation on Email field on registration page

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/volontulo#515]
Steps to reproduce:

- Go to login page (http://volontuloapp.org/login)
- Fill email address with more than 30 characters email
- Fill password
- Submit the form

Current behaviour:

- User is notified about Internal Server Error

Expected behaviour:

- Field should be validated
- User should be prompted, that email is longer than 30 characters

**Comment by magul** [comment]
I will create te validator there, but in future we should increase lenght of email field (see: https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#substituting-a-custom-user-model)

**Comment by magul** [comment]
Closing it as there's no Internal Error. Will resolve it, when it will be seen once more.
