### ISSUE TITLE
Limit access to pages for regular user and anonymous user

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/volontulo#521]
__Description:__

Remove access to pages for mentioned users (regular and anonymous):

1. /panel
2. offers/archived
3. offers/reorder

**Comment by magul** [comment]
@w1stler I have limited this change only to `Niezweryfikowane oferty` and `Kolejność ofert na stronie głównej` buttons as archived offers are available also from footer.

Removal of archived offers is not so critical, so if we want to do so, we can process it in separate issue after deploying first version of production.
