### ISSUE TITLE
Create Offers REST API endpoint

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#535]
__Description:__

We are decided to start implementing frontend in Angular 2+ and to do so we should have all objects in our system served in REST API.

This task is limited only to offers, rest of object will be moved in separate issues. 

__Current behaviour:__

No REST API available.

__Expected behaviour:__

Full REST API (with tests available).

**Comment by w1stler** [comment]
Seems to work as expected. I ran the unit tests and verified API calls for /organizations and /offers.
