### ISSUE TITLE
Django API-based login and logout endpoint unit tests

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#597]
__Description:__

Login and logout Django API endpoints need to be tested.

__Current behaviour:__

There are not tests for these endpoints.

__Expected behaviour:__

There are tests for these endpoints.

**Comment by magul** [comment]
It can wait for #694 - we will use fixtures here.

**Comment by KatyDi** [comment]
can I take?

**Comment by magul** [comment]
@KatyDi it's yours
