### ISSUE TITLE
Angular-based method to logout user

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#599]
__Description:__

We need option to logout user from our application inside Angular view.

__Current behaviour:__

There is no option to logout user from application inside Angular view.

__Expected behaviour:__

There exists option to logout user from application inside Angular view.

**Comment by ponycalypsenow** [comment]
assign to me.

**Comment by jacol12345** [comment]
Closed with https://github.com/CodeForPoznan/volontulo/pull/866
