### ISSUE TITLE
 Move 'FAQ dla organizacji' static page to the new Angular frontend

### ISSUE THREAD

**Issue by TrebuhD** [CodeForPoznan/volontulo#638]

**Comment by TrebuhD** [comment]
@dohko93

**Comment by juliaanholcer** [comment]
Since #674 pull request for this issue is closed due to lack of activity, may I take this issue?

**Comment by magul** [comment]
@juliaanholcer go for it!

**Comment by juliaanholcer** [comment]
While I'm removing old page from` backend/apps/volontulo/templates/pages/faq-organizations.html ` should I do something with ` test__get_organization_faq_staticpage` method in `backend/apps/volontulo/tests/views/test_pages.py`?

**Comment by jacol12345** [comment]
@juliaanholcer Yes, please remove this test as well.

**Comment by magul** [comment]
close in #760
