### ISSUE TITLE
Move static sites to the new Angular Frontend

### ISSUE THREAD

**Issue by TrebuhD** [CodeForPoznan/volontulo#640]
__Description:__

We should move all static pages to the new Angular version of the site.

__Current behaviour:__

All the static pages are currently only present in the old django based version of the site.

__Expected behaviour:__

- Static pages should be visible in the Angular version of the site.
- The static pages should be linked in the Footer.
- When a page is moved to the Angular site, it should be deleted from the old Django site.

**Comment by magul** [comment]
Done
