### ISSUE TITLE
Define release cycles

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#654]
As we are planning to go into production in near future, we need to define, how releasing our system will look like.

We need to decide, if we need 3 separate environments (development, release candidate, production)?
How often we will release new version? How long it will wait for regresion tests?

The technical way, how deployment will look like is out of the scope of this issue, but it include updating `README.md` with a chapter about release process.

**Comment by elspawaczo** [comment]
my thoughts:

As we have bigger boosts of development activities that are repeated in one week cycles (hacknights) we might look into 4-5 weeks productions cycles? 3-4 weeks for developing new features, after that we deploy it on RC - it sits there for one week during which we do regression tests, and fix bugs and after that one week we deploy on production.

so answering Your questions:
- 3 environments (dev, rc, prod),
- 4 or 5 week prod release cycles,
- one week for regression tests.

How is that?

**Comment by w1stler** [comment]
IMO that's fine.

**Comment by magul** [comment]
@w1stler can You, please write it as a part of `README.md`?

**Comment by w1stler** [comment]
PR raised: https://github.com/CodeForPoznan/volontulo/pull/732
