### ISSUE TITLE
Move register form from Django to Angular

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#686]
__Description:__

Move register form from Django to Angular

It contains spliting login and register to separate views (login stays in Django, Register is moved to Angular) and adding enpoint to register user through API.

__Current behaviour:__

Login and register is handled by Django.

__Expected behaviour:__

Login stays in Django, register is served by Angular.

**Comment by magul** [comment]
@lycathe

**Comment by jacekkalbarczyk** [comment]
Working on it.
