### ISSUE TITLE
Create user's fixtures factory

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#694]
Create factory, that will create pseudo-randomly user instances (with dependencies, like `UserProfile`) from a fixture.

For convinience all user should have the same password passed as an argument and be already active (no email confirmation required).

**Comment by MarekBleschke** [comment]
I'm thinking factory boy for test / data generation fixtures. @magul what do you think about this?

**Comment by magul** [comment]
@MarekBleschke there were an issue to decide what to do with that (see: #693 and #707). Can we also integrate Faker there, that will solve a lot name/address logic for us?

I know, that You know how to use it, don't be so shy :) https://github.com/joke2k/faker/commits?author=MarekBleschke
