### ISSUE TITLE
Change OffersComponent into HomepageOfferComponent 

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#699]
Right now we have only one instance of `OffersComponent` that handle all offers rendered on homepage. Instead of that we need to have for-loop in `HomeComponent` that render `HomepageOfferComponent` for every offer that should be shown on homepage.

It also require removal of unnecessary `  <h1>Main content</h1>`.

(Angular-based homepage will be visible after merging #690)

**Comment by Simon323** [comment]
Assign to me.

**Comment by Simon323** [comment]
Pull request: https://github.com/CodeForPoznan/volontulo/pull/737
