### ISSUE TITLE
Change name from HomeComponent into HomepageComponent

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#700]
Change `HomeComponent` into `HomepageComponent`.

This task also require changin `<volontulo-home>` selector into `<volontulo-homepage>` and all files (`ts`, `html` and `css`) from `home.component.*` into `homepage.component.*`

(Angular-based homepage will be visible after merging #690)

**Comment by KatyDi** [comment]
Asigne to me :)
