### ISSUE TITLE
Change links from old homepage into new one

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#704]
Homepage is right now handled by Angular instead of Django. We need to change all links, that link to old homepage to the new one.

This ticket require also removal of old Django-based url, view, template (with tests).

(Angular-based homepage will be visible after merging #690)

**Comment by magul** [comment]
@jacekkalbarczyk

**Comment by magul** [comment]
@Fenu321

**Comment by jacol12345** [comment]
All links to homepage in templates are replaced with links to Angular. We have some redirects to homepage in auth-related Django views and some tests. We'll get rid of the Django views when auth is moved to API. I'll take a look at why some tests not related to auth are actually using auth views.

**Comment by magul** [comment]
That was already done in https://github.com/CodeForPoznan/volontulo/commit/82311f20db29224763419ef04c3776d8db426a58
