### ISSUE TITLE
Wrong message on /offer/create

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/volontulo#723]
__Description:__

Kiedy użytkownik posiadający organizację, podczas tworzenia oferty, błędnie poda format daty (np. 01-12-2017 zamiast 2017-12-01) i kliknie `Zapisz ofertę`, otrzymuje komunikat:

 `Formularz zawiera niepoprawnie wypełnione pola <br />finished_at`

__Current behaviour:__

Komunikat brzmi:

`Formularz zawiera niepoprawnie wypełnione pola <br />finished_at`

__Expected behaviour:__

Komunikat powinien brzmieć:

`Formularz zawiera niepoprawnie wypełnione pola`

**Comment by magul** [comment]
Inne pole, ale dotyczy tego samego ekranu co #728, więc zamykam jako duplikat.
