### ISSUE TITLE
No message on /offer/create (Realizacja akcji)

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/volontulo#724]
__Description:__

Użytkownik tworząc nową ofertę może jako dzień rozpoczęcia akcji podać datę późniejszą, niż data jej zakończenia. Np:
`Dzień rozpoczęcia` 2017-12-01
`Dzień zakończenia` 2017-11-30
Po wciśnięciu przycisku `Zapisz ofertę` oferta jest zapisywana do bazy danych.

__Current behaviour:__

Formularz umożliwia wprowadzenie późniejszej daty rozpoczęcia akcji, niż data zakończenia.
Brak komunikatu o błędzie. Oferta jest zapisywana do bazy danych.

__Expected behaviour:__

Formularz powinien wyświetlić komunikat, że data rozpoczęcia akcji nie może być późniejsza, niż data zakończenia. Oferta nie powinna być zapisywana do bazy danych.

**Comment by ponycalypsenow** [comment]
Assign to me.

**Comment by w1stler** [comment]
To be verified.

**Comment by weronikafelczak** [comment]
Done with #825
