### ISSUE TITLE
Typo on o/me 

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/volontulo#727]
__Description:__

Typo on o/me (section "Aktywność") in sentence :
> Zgłoś się w jednej z dostępnych ofert wolontari**u**atu i zapełnij to miejsce. 

__Current behaviour:__

Sentence looks like:
> Zgłoś się w jednej z dostępnych ofert wolontari**u**atu i zapełnij to miejsce. 

__Expected behaviour:__

Sentence looks like:
> Zgłoś się w jednej z dostępnych ofert wolontariatu i zapełnij to miejsce.

**Comment by danutaj23** [comment]
Biorę!

**Comment by magul** [comment]
done in #730
