### ISSUE TITLE
Wrong message on /offer/create

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/volontulo#728]
__Description:__

Jeśli użytkownik podczas zakładania oferty nie wypełni wszystkich wymaganych pól (np. `Miejsce odbywania wolontariatu`, `Opis oferty`) otrzymuje komunikat:

 `Formularz zawiera niepoprawnie wypełnione pola <br />description<br />benefits<br />time_commitment`

__Current behaviour:__

Komunikat brzmi:

 `Formularz zawiera niepoprawnie wypełnione pola <br />description<br />benefits<br />time_commitment`

__Expected behaviour:__

Komunikat powinien brzmieć:

`Formularz zawiera niepoprawnie wypełnione pola`

**Comment by magul** [comment]
@danutaj23 o ile zgadzam się, że ten błąd jest niefartowny, to co do tego zgłoszenia mam kilka uwag:
 * to jest _stare_ Django, więc nie wiem czy jest sens tym się pilnie zajmować
 * w Angularze będziemy jako priorytet poprawiać flow wolontariusza, a tworzenie oferty jest zarezerwowane dla organizacji/instytucji, więc pewnie ten bug swoje poczeka (przypominam, że błąd występuje cały czas w _starym_ Django)
 * O ile są błędy w tym opisie, to pewnie chcielibyśmy  by się tam pojawiły informacje o polach, z którymi jest problem, czyli docelowo zamiast:
```
Formularz zawiera niepoprawnie wypełnione pola
```
powinno być:
```
Formularz zawiera niepoprawnie wypełnione pola:
 * Opis
 * Korzyści
 * Wymagania czasowe
```
no i te pola dodatkowo powinny świecić się na czerwono (to już jest też w _starym_ Django). Ale to pewnie też będziemy robić podczas przenosin do Angulara.
