### ISSUE TITLE
Limit wolontariuszy on /offer/create

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/volontulo#731]
__Description:__

Podczas wprowadzania oferty można ustawić limit wolontariuszy w Rekrutacji podstawowej, a w Rekrutacji dodatkowej już nie. Treść informacji znajdującej się obok formularza sugeruje, że powinno dać się ustalić limit wolontariuszy dla obu rekrutacji. Informacja brzmi: `Określ ramy czasowe (w formacie RRRR-MM-DD) oraz liczbę wolontariuszy, odpowiednio dla rezerwacji podstawowej i rozszerzonej.`

__Current behaviour:__

Brak możliwości ustalenia limitu wolontariuszy dla Rekrutacji rezerwowej lub błędna informacja o istnieniu takiej możliwości.

__Expected behaviour:__

Możliwość ustalenia limitu wolntariuszy dla Rekrutacji podstawowej i Rekrutacji rezerwowej.

**Comment by jacekkalbarczyk** [comment]
Biorę.
