### ISSUE TITLE
Angular-based organisation view

### ISSUE THREAD

**Issue by juliaanholcer** [CodeForPoznan/volontulo#741]
__Description:__

Create Angular-based component to show organisation details.

__Current behaviour:__

Organisation details are served by old Django-based view.

__Expected behaviour:__

Organisation details are served by Angular.

**Comment by juliaanholcer** [comment]
Assign to me.

**Comment by magul** [comment]
Closing this one, as we only need offer list there and there's already issue for that (see: #755)
