### ISSUE TITLE
Admin can access only unpublished offers

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/volontulo#746]
__Description:__

Admin can access only unpublished offers.

__Current behaviour:__

Admin can access only unpublished offers.

__Expected behaviour:__

Admin can access all offers.

Take a look at (`get_for_administrator`)
https://github.com/CodeForPoznan/volontulo/blob/master/backend/apps/volontulo/models.py#L42
```python
def get_for_administrator(self):
        """Return all offers for administrator to allow management."""
        return self.filter(offer_status='unpublished').all()
```

**Comment by jacekkalbarczyk** [comment]
Biorę.
