### ISSUE TITLE
Move Organizations List to Angular

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/volontulo#752]
__Description:__

List of organizations will be an Angular view, not Django.

To do:

1. Remove organization list from Django.
2. Add OrganizationListComponent to Angular.
3. Add OrgazniationListItemComponent to Angular
4. Add OrganizationService to Angular (if not already introduced by someone else).

Acceptance Criteria:

1. Organization list view works the same as previously.

**Comment by jacol12345** [comment]
@Fenu321

**Comment by Simon323** [comment]
Assign to me
