### ISSUE TITLE
Make the repo standalone, not a fork, to i.e. allow code search

### ISSUE THREAD

**Issue by radoslawroszkowiak** [CodeForPoznan/volontulo#856]
__Description:__

This repo is a fork of yet another dead (2 years) repository. One of the issues is some github features are not supported.

__Current behaviour:__

Code is not searchable
![image](https://user-images.githubusercontent.com/6575499/36982745-d5a4cb88-2090-11e8-920e-600a14ac15f5.png)

__Expected behaviour:__

Code can be searchable.

__Steps to reproduce:__

Just try to search some phrase in the repo, then click on the "code" in the left top corner.

**Comment by magul** [comment]
Just sent support request as described here: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

**Comment by magul** [comment]
They make `magul/volontulo` separate network, not `CodeForPoznan/volontulo` :/

**Comment by magul** [comment]
Done.
