### ISSUE TITLE
Personal data not prepopulated when contacting an organization

### ISSUE THREAD

**Issue by laziukiewicz** [CodeForPoznan/volontulo#865]
__Current behaviour__

W formularzu kontaktu z organizacją nie podpowiadają się dane osobowe wolontariusza, nawet jeśli są wypełnione w profilu użytkownika

__Expected behaviour__

Jeżeli użytkownik wypełnił swoje dane osobowe w profilu, powinny być wpisane automatycznie w formularzu kontaktu z organizacją.
//do rozważenia czy powinniśmy spójnie imię i nazwisko zapisywać w osobnych polach

__Steps to reproduce__

1. Wypełnij imię, nazwiko i telefon w profilu użytkownika
2. Przejdź do dowolnej strony kontaktu z organizacją (np. https://dev.volontulo.pl/o/organizations/wojewodzki-ogrod-zwiazkowy-totuus/1
3. Sprawdź prepopulowane dane (imię, nazwisko, email, telefon)

**Comment by magul** [comment]
@szeregowaD - > to be refined

**Comment by magul** [comment]
@dianawieczorek

**Comment by magul** [comment]
Done in #996
