### ISSUE TITLE
Organization list improper request handling

### ISSUE THREAD

**Issue by CorneeSean** [CodeForPoznan/volontulo#870]
__Description:__

Organization list is not loading properly in Angular due to improper request handling

__Current behaviour:__

Front-end request to "api/organizations" returns 301 Moved Permanently
Can be fixed on front-end by adding "/" at the end of the request url. It used to work properly before, tough, so I am not sure if we should solve it on front-end or back-end.

__Expected behaviour:__

Should return organization list with status 200.

__Steps to reproduce:__

Click on "Lista organizacji i instytucji". No organizations are being displayed. Server returns status 301.

**Comment by magul** [comment]
I was thinking about that a lot last 2 weeks but haven't found time to create an issue - I'm for requiring trailing slash at every API request, enforcing it on backend and frontend. What do You think?

**Comment by CorneeSean** [comment]
Let's do it with the trailing slash then. I will fix this current issue with organization list on frontend :)
