### ISSUE TITLE
Factory creates offers with finished_at date before started_at date

### ISSUE THREAD

**Issue by juliaanholcer** [CodeForPoznan/volontulo#876]
__Description:__

Factories create offers where date `started_at` is later than `finished_at` ~~and additionally `action_status` isn't as expected according to dates (e.g. offer has status future even if `startedAt` is past date)~~.

__Expected behaviour:__

Factories should validate dates ~and `action_status` shouldn't be chosen randomly but determined in the same way like while creating new offer (see: https://github.com/CodeForPoznan/volontulo/blob/master/backend/apps/volontulo/models.py#L194).~

__Steps to reproduce:__

populate_database and check some offers for dates ~~and status~~.

**Comment by magul** [comment]
@chessky
