### ISSUE TITLE
OfferFactory action_status based on action_start_date and action_end_date

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#908]
__Description:__

We need to make `action_status` depended on action dates.

__Current behaviour:__

`action_status` is totally random.

__Expected behaviour:__

`action_status` need to be:
 * `future` if `action_start_date` is in future
 * `ongoing if `action_start_date` is in past and `action_end_date` is in future
 * `finished` if `action_end_date` is in past

__Steps to reproduce:__

populate_database and check some offers for `action_status`.

**Comment by jacol12345** [comment]
https://github.com/CodeForPoznan/volontulo/pull/998
