### ISSUE TITLE
Volontulo logo in readme is not displayed

### ISSUE THREAD

**Issue by weronikafelczak** [CodeForPoznan/volontulo#937]
__Description:__

Volontulo logo in readme is not displayed, image source links to 404.

__Current behaviour:__

![logo](https://user-images.githubusercontent.com/32519132/39958527-90d9d0c6-5604-11e8-8448-cbb952c7196d.png)

__Expected behaviour:__

Logo in readme displays properly:
![screenshot from 2018-05-12 16-54-06](https://user-images.githubusercontent.com/32519132/39958570-24002396-5605-11e8-8a67-e41fc6648ad0.png)

Change source from `/backend/apps/volontulo/frontend/img/volo_logo.png` to: `frontend/src/assets/img/volo_logo.png`.

**Comment by magul** [comment]
@dianawieczorek
