### ISSUE TITLE
Start date and end date inputs are required make form invalid even when radio buttons are checked.

### ISSUE THREAD

**Issue by juliaanholcer** [CodeForPoznan/volontulo#950]
__Description:__

Start date and end date inputs are required make form invalid even when radio buttons are checked.

__Expected behaviour:__

Either radio button or date input should be required.

**Comment by weronikafelczak** [comment]
Done [https://github.com/CodeForPoznan/volontulo/pull/997](https://github.com/CodeForPoznan/volontulo/pull/997)
