### ISSUE TITLE
Add SPF records to DNS zone

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#961]
__Description:__

We need to define Sender Policy Framework for our domains.

Futher info:
* https://support.google.com/mail/answer/81126
* https://www.liquidweb.com/kb/what-is-an-spf-record/

For all our domains (`dev.volontulo.pl`, `rc.volontulo.pl` and `volontulo.pl`) set (3 separate TXT records): `v=spf1 a mx ~all`

**Comment by w1stler** [comment]
@magul SPF have been added, though there seems that this is not proper approach. I am reffering to these checks: https://mxtoolbox.com/domain/volontulo.pl/

**Comment by w1stler** [comment]
Removed.

**Comment by magul** [comment]
@w1stler right now it looks, that You removed two SPF records, not only the one we need to remove:
```
dig volontulo.pl txt

; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>> volontulo.pl txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49434
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;volontulo.pl.			IN	TXT

;; ANSWER SECTION:
volontulo.pl.		3600	IN	TXT	"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC9n6V6R/ObTkUaiU2TnVzO9rj4IseNjeUFiYlZS1gPq1J2WjXT+HyuHd2OyHTqe8FNXaP9bEg25GxBtFaLOzTg4llpdqcseB9+6slaXMzOuhc3S2L+x9PEnzKDYSwtnB0b/iFJ6wx7hId/tI3I/aq2p1iM9J9u/T3aSQOk80SuUwIDAQAB"
volontulo.pl.		3600	IN	TXT	"google-site-verification=WD14vcGEK_uaPOiIC1Sr_0hN8YGP8NyVwk1upkQybqg"

;; Query time: 39 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon May 28 11:58:53 CEST 2018
;; MSG SIZE  rcvd: 369

```
There need to be one defined:
```
volontulo.pl.		3583	IN	TXT	"v=spf1 a mx ~all"
```

**Comment by magul** [comment]
oh! I see, You removed SPF records from domain, leave DKIM (which should be moved to `mail._domainkey` subdomain) and instead of moving DKIM You created SPF record there.

Please clean this mess.

**Comment by magul** [comment]
(and it apply to all domains, that there issues are about: `volontulo.pl`, `rc.volontulo.pl` and `dev.volontulo.pl`)
