### ISSUE TITLE
Add DMARC records to DNS zone

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#962]
To improve ours mailservers deliverability we need to implement DMARC, to do so we need to add specific TXT record to 3 domains in our DNS zone (this is `_dmarc.dev.volontulo.pl`, `_dmarc.rc.volontulo.pl` and `_dmarc.volontulo.pl`).

The TXT record is: `v=DMARC1; p=quarantine; rua=mailto:hello@codeforpoznan.pl; ruf=mailto:hello@codeforpoznan.pl; sp=reject; ri=86400`

After adding these record we can check if it's properly impemented here: https://dmarcguide.globalcyberalliance.org/#/

**Comment by w1stler** [comment]
Done.
