### ISSUE TITLE
Use organizations-list component on user's account page

### ISSUE THREAD

**Issue by beerkoo** [CodeForPoznan/volontulo#975]
Use component 'Organizations-list' on user account view to display all available organizations you're a member of. Needs to use a list of organizations from current user's organizations property.
Display this component only if the user owns min. one organization. 

EDIT: Use it also for users organizations list on account page (developed in #966)

**Comment by juliaanholcer** [comment]
An idea to discuss: Organizations component should contain a title, button to add organization and organizations-list component, that will take a list of organizations as an input. For all organizations main view it will take organizations using service that fetch data from backend. Organizations-list component can be reused in MeComponent, when input will be provided from current-user (subscription to user$ from auth.service).

**Comment by magul** [comment]
Can You move this `idea to discuss` to separate issue @juliaanholcer ? I believe, that it will be lose here.
