### ISSUE TITLE
API endpoint to change current user password

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#983]
To provide a simple way to update current user password we need to add a and API endpoint to do so.

POST payload should contains:
 * current password,
 * new password
fields.

**Comment by magul** [comment]
@jacol12345 I moved you here, as I haven't spot before that @Brzozova is working on #971

**Comment by jacol12345** [comment]
https://github.com/CodeForPoznan/volontulo/pull/1008
