### ISSUE TITLE
Add an enpoint, to list all offers, that current user joined

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#985]
I would say that in some future this should be a pagination-enabled endpoint, for maybe for now we could attach this data to `/api/current-user` endpoint under some attribute?

**Comment by kristhina** [comment]
working on it

**Comment by kristhina** [comment]
29.08.2018 - pull request

**Comment by magul** [comment]
You can start using that: https://help.github.com/articles/closing-issues-using-keywords/

@kristhina

**Comment by kristhina** [comment]
Thanks, next time I will try to remember.
